### PR TITLE
axes convention in mudata

### PR DESCRIPTION
**Pull request by grst**
TODO before merge: 

- [ ] fix links (some of them point to other pages, so those need to be merged first)
- [ ] Fix TODOs in notebook

### CODE REVIEW

**Comment by grst** [comment]
@bio-la, any chance you could give this another iteration? I don't think there's missing anything substantial and it would be a waste to never merge this :)

**Comment by bio-la** [comment]
Dammit i completely forgot about this! Sorry, I'm so embarrassed! Will get to it tomorrow :)

**Comment by bio-la** [comment]
implemented the changes @grst  i am not sure why readthedocs fails.

**Comment by grst** [comment]
Thanks, Fabiola!

**Pull request merged**
