### PR TITLE
cellcharter tutorial

### PR DESCRIPTION
**Pull request by mengerj**

### CODE REVIEW

**Comment by canergen** [comment]
Hi, do you plan contributing CellCharter to scvi-tools or did you not set the repo upstream correctly?

**Comment by mengerj** [comment]
I am trying to add the cellcharter tutorial to the scverse-tutorial repo, so that it appears on the website. Am I doing it wrong? I don't want to add anything to scvi-tools.

**Comment by mengerj** [comment]
Ah alright, no worries ^^

**Comment by grst** [comment]
part of #190

**Pull request closed without merging**
