### PR TITLE
Stop pointing at scanpy-tutorials

### PR DESCRIPTION
**Pull request by ivirshup**
Moved links for plotting tutorials to point at scanpy docs, since these tutorials are hosted there now.

### CODE REVIEW

**Review by grst — APPROVED** [review]

**Comment by ivirshup** [comment]
Oof, is this going to have to re-run the notebook since I updated a line?

**Comment by grst** [comment]
yes, that's expected... and now everything falls apart, which is also somewhat expected since nobody executed the notebooks in half a year.

**Comment by ivirshup** [comment]
I can probably make a release of scanpy that exposes the `sc.external.pp.scrublet` but just redirects to `sc.pp.scrublet`, then revert changes to the notebook? We probably should be redirecting for that anyways.

**Comment by grst** [comment]
yeah that could work as a quick fix. But at some point we'll have to take a look at the notebooks either way.

**Comment by flying-sheep** [comment]
@grst seems like without a cache entry, this fails. What shall we do?

**Comment by grst** [comment]
5/6 notebooks have passed, not so bad. 

The actual error is

```pytb
 ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [40], line 1
----> 1 dc.run_mlm(mat=adata, net=markers, weight=None, source="cell_type", target="genesymbol", verbose=True, use_raw=False)

File /usr/share/miniconda3/envs/tutorials/lib/python3.10/site-packages/decoupler/method_mlm.py:116, in run_mlm(mat, net, source, target, weight, batch_size, min_n, verbose, use_raw)
    114 # Transform net
    115 net = rename_net(net, source=source, target=target, weight=weight)
--> 116 net = filt_min_n(c, net, min_n=min_n)
    117 sources, targets, net = get_net_mat(net)
    119 # Match arrays

File /usr/share/miniconda3/envs/tutorials/lib/python3.10/site-packages/decoupler/pre.py:149, in filt_min_n(c, net, min_n)
    146 net = net[msk]
    148 if net.shape[0] == 0:
--> 149     raise ValueError("""No sources with more than min_n={0} targets. Make sure mat and net have shared target features or
    150     reduce the number assigned to min_n""".format(min_n))
    152 return net

ValueError: No sources with more than min_n=5 targets. Make sure mat and net have shared target features or
        reduce the number assigned to min_n
ValueError: No sources with more than min_n=5 targets. Make sure mat and net have shared target features or
        reduce the number assigned to min_n
```

in the basic tutorial. I might be able to take a look tomorrow, but can't guarantee.

**Comment by ivirshup** [comment]
@grst, I think we may want to revert this and rethink a little. The cluster labellings in the "preprocessing and clustering" tutorial are now incorrect.


797bc9d62f3d846b2acee072a6ab1793e2f98d7e459215cb67dd6b40dc1de7fc


I think it is highly unlikely that bottom group contains:

* B cells
* Proerythroblasts
* And CD4+ T cells

I think it's all going to be B cells

Here are CellTypist's predictions, and enrichment scores using Pangalao markers. Both show that grouping to be B-cells

af874d53dd02ef637546d88cd571971c119a71a88aa3d38b1152fe4f6b049a27

**Pull request merged**
