### PR TITLE
scverse data - backed mode tutorial

### PR DESCRIPTION
**Pull request by emdann**
First draft of tutorial on working with scverse data objects in backed mode

Outstanding issues/questions
---
- No mention of zarr containers?
- Where to store data objects? Currently in `data/`, created by `scanpy.datasets`

To do
----
- [x] sort out kernel specifications

### CODE REVIEW

**Comment by grst** [comment]
currently failing with: 

```
File /usr/share/miniconda3/envs/tutorials/lib/python3.10/site-packages/scanpy/preprocessing/_normalization.py:191, in normalize_total(adata, target_sum, exclude_highly_expressed, max_fraction, key_added, layer, layers, layer_norm, inplace, copy)
    189     counts_per_cell = X[:, gene_subset].sum(1)
    190 else:
--> 191     counts_per_cell = X.sum(1)
    192 start = logg.info(msg)
    193 counts_per_cell = np.ravel(counts_per_cell)

AttributeError: 'SparseDataset' object has no attribute 'sum'
```

**Comment by emdann** [comment]
Ah LOL I made it so that it would show an error that you might get, but I didn't think that would break CI. Should I just put traceback in a md code block?

**Comment by emdann** [comment]
I've added a note as markdown, I think this is fine for now

**Comment by grst** [comment]
oh, I think we need some gitignores
```
remote: error: File docs/notebooks/data/pbmc10k_multiome.NKTcells.h5mu is 630.67 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: File docs/notebooks/data/pbmc10k_multiome.h5mu is 1115.51 MB; this exceeds GitHub's file size limit of 100.00 MB       
```

**Comment by emdann** [comment]
<p>mmm not sure, suggestions welcome here</p>

---

 <a href='https://app.reviewnb.com/scverse/scverse-tutorials/pull/24/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by emdann** [comment]
<p><code>.to_memory()</code> is not implemented in MuData as far as I can tell </p>

---

 <a href='https://app.reviewnb.com/scverse/scverse-tutorials/pull/24/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by grst** [comment]
<p>I added a <code>filterwarning</code></p>

---

 <a href='https://app.reviewnb.com/scverse/scverse-tutorials/pull/24/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by grst — APPROVED** [review]
LGTM

**Pull request merged**
